#!/usr/bin/env python3
import argparse
import os

TEMPLATE = """# Isoform Report

This report summarizes isoform proportions for selected genes across samples.

## Figures

{figs_section}

Generated by SpliceVariantAnalysisPipeline.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--figs', nargs='+', required=True, help='List of figure PNGs')
    ap.add_argument('--out', required=True, help='Output markdown path')
    args = ap.parse_args()

    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    lines = []
    for fig in args.figs:
        name = os.path.basename(fig)
        gene = name.replace('_proportions.png', '')
        lines.append(f"### {gene}\n\n")
        lines.append(f"![]({fig})\n\n")

    with open(args.out, 'w') as f:
        f.write(TEMPLATE.format(figs_section=''.join(lines)))

if __name__ == '__main__':
    main()
