# Pipeline configuration file for SpliceVariantAnalysisPipeline
# Edit this file to specify paths, resources, and analysis options

# Path to sample sheet (CSV)
samples_csv: config/samples.csv

# Reference files
reference:
  genome_fa: data/reference/genome.fa
  transcripts_fa: data/reference/transcripts.fa
  gtf: data/reference/reference.gtf

# Salmon index directory
salmon_index: data/reference/salmon_index

# HISAT2 index directory
hisat2_index: data/reference/hisat2_index

# Output directories (organized under output/)
analysis_dir: output/analysis
trimmed_dir: output/trimmed
salmon_quant_dir: output/salmon_quant
alignments_dir: output/alignments
logs_dir: output/logs

# Analysis options
qc:
  run_fastqc: true
  run_trimming: true
  trimmer: fastp  # or TrimGalore

salmon:
  kmer_size: 31
  threads: 8

hisat2:
  threads: 8
  dta: true

stringtie:
  merge: true
  compare: true

r_analysis:
  genes_of_interest:
    - MS4A4A
    - MS4A6A
  dtu_method: DRIMSeq  # or IsoformSwitchAnalyzeR

# Plotting options
plots:
  # 'proportion' or 'NumReads'
  figure_metric: NumReads

# Add more options as needed
